In [5]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Phishing_Clened_EDA_data.csv')

In [3]:
df.head()

Total-character  Uppercase_letter  Lowercase_letter  Total_numbers  \
0              225                 2               133             58   
1               81                 0                65              1   
2              177                 0               111             47   
3               60                 0                52              0   
4              116                12                70             21   

   Total_symbol  Total_slesh  Total_dots  Total_desh  Label  
0            32           10           6           4      0  
1            15            4           5           2      0  
2            19           11           7           1      0  
3             8            2           6           0      0  
4            13           10           1           1      0

In [4]:
df.shape

(549346, 9)

In [5]:
# convert depedent and indepedent feature
X = df.drop(['Label'],axis=1)
y = df['Label']

In [6]:
X.head()

Total-character  Uppercase_letter  Lowercase_letter  Total_numbers  \
0              225                 2               133             58   
1               81                 0                65              1   
2              177                 0               111             47   
3               60                 0                52              0   
4              116                12                70             21   

   Total_symbol  Total_slesh  Total_dots  Total_desh  
0            32           10           6           4  
1            15            4           5           2  
2            19           11           7           1  
3             8            2           6           0  
4            13           10           1           1

In [7]:
y.value_counts()

Label
1    392924
0    156422
Name: count, dtype: int64

In [8]:
# convert into X_train and test
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)

In [10]:
X_train.shape,X_test.shape

((384542, 8), (164804, 8))

In [11]:
y_train.value_counts(),y_test.value_counts()

(Label
 1    274870
 0    109672
 Name: count, dtype: int64,
 Label
 1    118054
 0     46750
 Name: count, dtype: int64)

In [12]:
# scaling tha data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [13]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [14]:
X_train_scaled

array([[-0.73790045, -0.19418911, -0.87292671, ..., -0.90626831,
        -0.70308642, -0.05274225],
       [ 0.47901566,  0.08031588,  0.60104817, ...,  0.97094411,
        -0.70308642, -0.05274225],
       [-0.37733272,  0.17181755, -0.47455512, ..., -0.28053084,
        -0.04057017, -0.46415897],
       ...,
       [-0.94071981, -0.19418911, -1.19162398, ..., -0.90626831,
        -0.70308642, -0.46415897],
       [-0.3998682 , -0.19418911, -0.35504365, ..., -0.90626831,
         1.28446234, -0.46415897],
       [-0.49001013, -0.19418911, -0.47455512, ...,  0.34520664,
        -0.70308642, -0.46415897]], shape=(384542, 8))

In [15]:
# model training
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB


In [16]:
models = {
    'LogisticRegression':LogisticRegression(),
    # 'SVC':SVC(),
    'DecisionTreeClassifier':DecisionTreeClassifier(),
    # 'KNeighborsClassifier':KNeighborsClassifier(),
    'RandomForestClassifier':RandomForestClassifier(),
    'AdaBoostClassifier':AdaBoostClassifier(),
    'GradientBoostingClassifier':GradientBoostingClassifier(),
    'GaussianNB':GaussianNB()
}

In [17]:
models

{'LogisticRegression': LogisticRegression(),
 'DecisionTreeClassifier': DecisionTreeClassifier(),
 'RandomForestClassifier': RandomForestClassifier(),
 'AdaBoostClassifier': AdaBoostClassifier(),
 'GradientBoostingClassifier': GradientBoostingClassifier(),
 'GaussianNB': GaussianNB()}

In [18]:
# calculate score
from sklearn.metrics import accuracy_score

In [19]:
def model_eveluate(y_real,y_pred):
    acc_score = accuracy_score(y_real,y_pred)
    return acc_score

In [21]:
model_list = []
acc_score = []
for i in range(len(list(models))):

    model = list(models.values())[i]
    model.fit(X_train_scaled,y_train)
    
    
    
    # prediction
    y_train_pred = model.predict(X_train_scaled)
    y_test_pred = model.predict(X_test_scaled)
    
    
    # calcualte score
    train_score = model_eveluate(y_train,y_train_pred)
    test_score = model_eveluate(y_test,y_test_pred)
   
    
    # printing score
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])
    
    
    print('Model Performance')
    print('Train accuracy_score :{:.4f}'.format(train_score))
    print('Test accuracy_score :{:.4f}'.format(test_score))
    
    
    acc_score.append(test_score)
    
    
    print('='*35)
    print('\n')
    
    
    

LogisticRegression
Model Performance
Train accuracy_score :0.7706
Test accuracy_score :0.7715


DecisionTreeClassifier
Model Performance
Train accuracy_score :0.9024
Test accuracy_score :0.8581


RandomForestClassifier
Model Performance
Train accuracy_score :0.9024
Test accuracy_score :0.8681


AdaBoostClassifier
Model Performance
Train accuracy_score :0.7762
Test accuracy_score :0.7772


GradientBoostingClassifier
Model Performance
Train accuracy_score :0.8278
Test accuracy_score :0.8292


GaussianNB
Model Performance
Train accuracy_score :0.7660
Test accuracy_score :0.7671




In [20]:
model = RandomForestClassifier()

In [21]:
model.fit(X_train_scaled,y_train)

RandomForestClassifier()

In [22]:
model.classes_

array([0, 1])

In [23]:
y_pred = model.predict(X_test_scaled)

In [24]:
y_pred

array([1, 1, 0, ..., 1, 1, 1], shape=(164804,))

In [25]:
# calculate the score and confusion metrix
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,roc_auc_score

In [27]:
score = accuracy_score(y_test,y_pred)
report = classification_report(y_test,y_pred)
matrix = confusion_matrix(y_test,y_pred)
roc_score = roc_auc_score(y_test,y_pred)



In [28]:
print(f'accuracy_score:{score}')
print('Classification_report:\n {}'.format(report))
print(f'confusion_matrix:\n {matrix}')
print(f'roc_auc_score:{roc_auc_score}')

accuracy_score:0.8686075580689789
Classification_report:
               precision    recall  f1-score   support

           0       0.83      0.67      0.74     46750
           1       0.88      0.95      0.91    118054

    accuracy                           0.87    164804
   macro avg       0.86      0.81      0.83    164804
weighted avg       0.87      0.87      0.86    164804

confusion_matrix:
 [[ 31297  15453]
 [  6201 111853]]
roc_auc_score:<function roc_auc_score at 0x000001BB9C313E20>


In [29]:
# 0-->bed 1-->good
y_test.value_counts()

Label
1    118054
0     46750
Name: count, dtype: int64

In [30]:
# save model
import pickle

In [31]:
with open('../Random_forest_model.pkl','wb') as file:
    pickle.dump(model,file)

In [32]:
# save standerad scaler
with open('../scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

# make prediction

In [1]:
import string
symbol = string.punctuation
unique_symbol = '!"#$%&\'()*+,:;<=>?@[\\]^_`{|}~'
def String_analysis(url):
    return {
        
        'Total-character':len(url),
        'Uppercase_letter':sum(1 for char in url if char.isupper()),
        'Lowercase_letter':sum(1 for char in url if char.islower()),
        'Total_numbers':sum(1 for char in url if char.isdigit()),
        'Total_symbol':sum(1 for char in url if char in symbol),
        'Total_slesh':sum(1 for char in url if char == '/'),
        'Total_dots':sum(1 for char in url if char == '.'),
        'Total_desh':sum(1 for char in url if char == '-'),
        
    }

In [20]:
url = "https://www.youtube.com/watch?v=qd0LWPe0oCU"

url_dict = String_analysis(url)

In [21]:
url_dict

{'Total-character': 43,
 'Uppercase_letter': 5,
 'Lowercase_letter': 28,
 'Total_numbers': 2,
 'Total_symbol': 8,
 'Total_slesh': 3,
 'Total_dots': 2,
 'Total_desh': 0}

In [22]:
# convert into datafream
url_datafream = pd.DataFrame(url_dict,index=[0])
url_datafream.head()

Total-character  Uppercase_letter  Lowercase_letter  Total_numbers  \
0               43                 5                28              2   

   Total_symbol  Total_slesh  Total_dots  Total_desh  
0             8            3           2           0

In [23]:
# load model
import pickle

with open('../Random_forest_model.pkl','rb') as file:
    model = pickle.load(file)
with open('../scaler.pkl','rb') as file:
    scaler = pickle.load(file)

In [24]:
# scal the value
url_scaled = scaler.transform(url_datafream)
url_scaled

array([[-0.17451336,  0.26331921, -0.35504365, -0.23990508,  0.18380142,
         0.34520664, -0.04057017, -0.46415897]])

In [25]:
prediction = model.predict(url_scaled)
print(prediction)

[1]


In [26]:
print(prediction[0])

1


In [27]:
if prediction[0] == 0:
    print(f'URL : {url} is Bed')
else:
    print(f'URL : {url} is safe')

URL : https://www.youtube.com/watch?v=qd0LWPe0oCU is safe
